// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.2
// - protoc             v3.12.0
// source: agent/service/v1/agent_service.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAgentServiceAddMCPService = "/api.agent.service.v1.AgentService/AddMCPService"
const OperationAgentServiceChat = "/api.agent.service.v1.AgentService/Chat"
const OperationAgentServiceCreateAgent = "/api.agent.service.v1.AgentService/CreateAgent"
const OperationAgentServiceDeleteAgent = "/api.agent.service.v1.AgentService/DeleteAgent"
const OperationAgentServiceGetAgent = "/api.agent.service.v1.AgentService/GetAgent"
const OperationAgentServiceGetMCPServiceTools = "/api.agent.service.v1.AgentService/GetMCPServiceTools"
const OperationAgentServiceListAgentTypes = "/api.agent.service.v1.AgentService/ListAgentTypes"
const OperationAgentServiceListAgents = "/api.agent.service.v1.AgentService/ListAgents"
const OperationAgentServiceListMCPServices = "/api.agent.service.v1.AgentService/ListMCPServices"
const OperationAgentServiceListMCPServicesWithId = "/api.agent.service.v1.AgentService/ListMCPServicesWithId"
const OperationAgentServiceListTools = "/api.agent.service.v1.AgentService/ListTools"
const OperationAgentServiceRemoveMCPService = "/api.agent.service.v1.AgentService/RemoveMCPService"
const OperationAgentServiceUpdateAgent = "/api.agent.service.v1.AgentService/UpdateAgent"

type AgentServiceHTTPServer interface {
	// AddMCPService MCP 服务管理
	AddMCPService(context.Context, *MCPServiceRequest) (*MCPServiceResponse, error)
	// Chat 单次对话请求
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	// CreateAgent Agent 管理
	CreateAgent(context.Context, *AgentConfigRequest) (*AgentConfigResponse, error)
	DeleteAgent(context.Context, *AgentDeleteRequest) (*AgentConfigResponse, error)
	GetAgent(context.Context, *AgentGetRequest) (*AgentConfigResponse, error)
	GetMCPServiceTools(context.Context, *MCPServiceToolsRequest) (*MCPServiceToolsResponse, error)
	// ListAgentTypes 获取可用的Agent类型
	ListAgentTypes(context.Context, *Empty) (*AgentTypesResponse, error)
	ListAgents(context.Context, *Empty) (*AgentListResponse, error)
	ListMCPServices(context.Context, *Empty) (*MCPServicesResponse, error)
	ListMCPServicesWithId(context.Context, *Empty) (*MCPServicesWithIdResponse, error)
	// ListTools 获取可用的工具列表
	ListTools(context.Context, *Empty) (*ToolsResponse, error)
	RemoveMCPService(context.Context, *MCPServiceRequest) (*MCPServiceResponse, error)
	UpdateAgent(context.Context, *AgentConfigRequest) (*AgentConfigResponse, error)
}

func RegisterAgentServiceHTTPServer(s *http.Server, srv AgentServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/chat", _AgentService_Chat0_HTTP_Handler(srv))
	r.GET("/api/agent-types", _AgentService_ListAgentTypes0_HTTP_Handler(srv))
	r.GET("/api/tools", _AgentService_ListTools0_HTTP_Handler(srv))
	r.POST("/api/mcp/services", _AgentService_AddMCPService0_HTTP_Handler(srv))
	r.DELETE("/api/mcp/services/{name}", _AgentService_RemoveMCPService0_HTTP_Handler(srv))
	r.GET("/api/mcp/services", _AgentService_ListMCPServices0_HTTP_Handler(srv))
	r.GET("/api/mcp/services-with-id", _AgentService_ListMCPServicesWithId0_HTTP_Handler(srv))
	r.GET("/api/mcp/services/{id}/tools", _AgentService_GetMCPServiceTools0_HTTP_Handler(srv))
	r.POST("/api/agents", _AgentService_CreateAgent0_HTTP_Handler(srv))
	r.PUT("/api/agents/{id}", _AgentService_UpdateAgent0_HTTP_Handler(srv))
	r.DELETE("/api/agents/{id}", _AgentService_DeleteAgent0_HTTP_Handler(srv))
	r.GET("/api/agents/{id}", _AgentService_GetAgent0_HTTP_Handler(srv))
	r.GET("/api/agents", _AgentService_ListAgents0_HTTP_Handler(srv))
}

func _AgentService_Chat0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChatRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceChat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Chat(ctx, req.(*ChatRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentService_ListAgentTypes0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceListAgentTypes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAgentTypes(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentTypesResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentService_ListTools0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceListTools)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTools(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ToolsResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentService_AddMCPService0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MCPServiceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceAddMCPService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddMCPService(ctx, req.(*MCPServiceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MCPServiceResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentService_RemoveMCPService0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MCPServiceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceRemoveMCPService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveMCPService(ctx, req.(*MCPServiceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MCPServiceResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentService_ListMCPServices0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceListMCPServices)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMCPServices(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MCPServicesResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentService_ListMCPServicesWithId0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceListMCPServicesWithId)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMCPServicesWithId(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MCPServicesWithIdResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentService_GetMCPServiceTools0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MCPServiceToolsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceGetMCPServiceTools)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMCPServiceTools(ctx, req.(*MCPServiceToolsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MCPServiceToolsResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentService_CreateAgent0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AgentConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceCreateAgent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAgent(ctx, req.(*AgentConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentConfigResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentService_UpdateAgent0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AgentConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceUpdateAgent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAgent(ctx, req.(*AgentConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentConfigResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentService_DeleteAgent0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AgentDeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceDeleteAgent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAgent(ctx, req.(*AgentDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentConfigResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentService_GetAgent0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AgentGetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceGetAgent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAgent(ctx, req.(*AgentGetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentConfigResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentService_ListAgents0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceListAgents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAgents(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentListResponse)
		return ctx.Result(200, reply)
	}
}

type AgentServiceHTTPClient interface {
	AddMCPService(ctx context.Context, req *MCPServiceRequest, opts ...http.CallOption) (rsp *MCPServiceResponse, err error)
	Chat(ctx context.Context, req *ChatRequest, opts ...http.CallOption) (rsp *ChatResponse, err error)
	CreateAgent(ctx context.Context, req *AgentConfigRequest, opts ...http.CallOption) (rsp *AgentConfigResponse, err error)
	DeleteAgent(ctx context.Context, req *AgentDeleteRequest, opts ...http.CallOption) (rsp *AgentConfigResponse, err error)
	GetAgent(ctx context.Context, req *AgentGetRequest, opts ...http.CallOption) (rsp *AgentConfigResponse, err error)
	GetMCPServiceTools(ctx context.Context, req *MCPServiceToolsRequest, opts ...http.CallOption) (rsp *MCPServiceToolsResponse, err error)
	ListAgentTypes(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *AgentTypesResponse, err error)
	ListAgents(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *AgentListResponse, err error)
	ListMCPServices(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *MCPServicesResponse, err error)
	ListMCPServicesWithId(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *MCPServicesWithIdResponse, err error)
	ListTools(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *ToolsResponse, err error)
	RemoveMCPService(ctx context.Context, req *MCPServiceRequest, opts ...http.CallOption) (rsp *MCPServiceResponse, err error)
	UpdateAgent(ctx context.Context, req *AgentConfigRequest, opts ...http.CallOption) (rsp *AgentConfigResponse, err error)
}

type AgentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAgentServiceHTTPClient(client *http.Client) AgentServiceHTTPClient {
	return &AgentServiceHTTPClientImpl{client}
}

func (c *AgentServiceHTTPClientImpl) AddMCPService(ctx context.Context, in *MCPServiceRequest, opts ...http.CallOption) (*MCPServiceResponse, error) {
	var out MCPServiceResponse
	pattern := "/api/mcp/services"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentServiceAddMCPService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentServiceHTTPClientImpl) Chat(ctx context.Context, in *ChatRequest, opts ...http.CallOption) (*ChatResponse, error) {
	var out ChatResponse
	pattern := "/api/chat"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentServiceChat))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentServiceHTTPClientImpl) CreateAgent(ctx context.Context, in *AgentConfigRequest, opts ...http.CallOption) (*AgentConfigResponse, error) {
	var out AgentConfigResponse
	pattern := "/api/agents"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentServiceCreateAgent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentServiceHTTPClientImpl) DeleteAgent(ctx context.Context, in *AgentDeleteRequest, opts ...http.CallOption) (*AgentConfigResponse, error) {
	var out AgentConfigResponse
	pattern := "/api/agents/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceDeleteAgent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentServiceHTTPClientImpl) GetAgent(ctx context.Context, in *AgentGetRequest, opts ...http.CallOption) (*AgentConfigResponse, error) {
	var out AgentConfigResponse
	pattern := "/api/agents/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceGetAgent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentServiceHTTPClientImpl) GetMCPServiceTools(ctx context.Context, in *MCPServiceToolsRequest, opts ...http.CallOption) (*MCPServiceToolsResponse, error) {
	var out MCPServiceToolsResponse
	pattern := "/api/mcp/services/{id}/tools"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceGetMCPServiceTools))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentServiceHTTPClientImpl) ListAgentTypes(ctx context.Context, in *Empty, opts ...http.CallOption) (*AgentTypesResponse, error) {
	var out AgentTypesResponse
	pattern := "/api/agent-types"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceListAgentTypes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentServiceHTTPClientImpl) ListAgents(ctx context.Context, in *Empty, opts ...http.CallOption) (*AgentListResponse, error) {
	var out AgentListResponse
	pattern := "/api/agents"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceListAgents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentServiceHTTPClientImpl) ListMCPServices(ctx context.Context, in *Empty, opts ...http.CallOption) (*MCPServicesResponse, error) {
	var out MCPServicesResponse
	pattern := "/api/mcp/services"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceListMCPServices))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentServiceHTTPClientImpl) ListMCPServicesWithId(ctx context.Context, in *Empty, opts ...http.CallOption) (*MCPServicesWithIdResponse, error) {
	var out MCPServicesWithIdResponse
	pattern := "/api/mcp/services-with-id"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceListMCPServicesWithId))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentServiceHTTPClientImpl) ListTools(ctx context.Context, in *Empty, opts ...http.CallOption) (*ToolsResponse, error) {
	var out ToolsResponse
	pattern := "/api/tools"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceListTools))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentServiceHTTPClientImpl) RemoveMCPService(ctx context.Context, in *MCPServiceRequest, opts ...http.CallOption) (*MCPServiceResponse, error) {
	var out MCPServiceResponse
	pattern := "/api/mcp/services/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceRemoveMCPService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentServiceHTTPClientImpl) UpdateAgent(ctx context.Context, in *AgentConfigRequest, opts ...http.CallOption) (*AgentConfigResponse, error) {
	var out AgentConfigResponse
	pattern := "/api/agents/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentServiceUpdateAgent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
