// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.0
// source: agent/service/v1/agent_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Chat_FullMethodName                  = "/api.agent.service.v1.AgentService/Chat"
	AgentService_StreamChat_FullMethodName            = "/api.agent.service.v1.AgentService/StreamChat"
	AgentService_ListAgentTypes_FullMethodName        = "/api.agent.service.v1.AgentService/ListAgentTypes"
	AgentService_ListTools_FullMethodName             = "/api.agent.service.v1.AgentService/ListTools"
	AgentService_AddMCPService_FullMethodName         = "/api.agent.service.v1.AgentService/AddMCPService"
	AgentService_RemoveMCPService_FullMethodName      = "/api.agent.service.v1.AgentService/RemoveMCPService"
	AgentService_ListMCPServices_FullMethodName       = "/api.agent.service.v1.AgentService/ListMCPServices"
	AgentService_ListMCPServicesWithId_FullMethodName = "/api.agent.service.v1.AgentService/ListMCPServicesWithId"
	AgentService_GetMCPServiceTools_FullMethodName    = "/api.agent.service.v1.AgentService/GetMCPServiceTools"
	AgentService_CreateAgent_FullMethodName           = "/api.agent.service.v1.AgentService/CreateAgent"
	AgentService_UpdateAgent_FullMethodName           = "/api.agent.service.v1.AgentService/UpdateAgent"
	AgentService_DeleteAgent_FullMethodName           = "/api.agent.service.v1.AgentService/DeleteAgent"
	AgentService_GetAgent_FullMethodName              = "/api.agent.service.v1.AgentService/GetAgent"
	AgentService_ListAgents_FullMethodName            = "/api.agent.service.v1.AgentService/ListAgents"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent服务定义（Kratos风格）
type AgentServiceClient interface {
	// 单次对话请求
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	// 流式对话请求
	StreamChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamResponse], error)
	// 获取可用的Agent类型
	ListAgentTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentTypesResponse, error)
	// 获取可用的工具列表
	ListTools(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ToolsResponse, error)
	// MCP 服务管理
	AddMCPService(ctx context.Context, in *MCPServiceRequest, opts ...grpc.CallOption) (*MCPServiceResponse, error)
	RemoveMCPService(ctx context.Context, in *MCPServiceRequest, opts ...grpc.CallOption) (*MCPServiceResponse, error)
	ListMCPServices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MCPServicesResponse, error)
	ListMCPServicesWithId(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MCPServicesWithIdResponse, error)
	GetMCPServiceTools(ctx context.Context, in *MCPServiceToolsRequest, opts ...grpc.CallOption) (*MCPServiceToolsResponse, error)
	// Agent 管理
	CreateAgent(ctx context.Context, in *AgentConfigRequest, opts ...grpc.CallOption) (*AgentConfigResponse, error)
	UpdateAgent(ctx context.Context, in *AgentConfigRequest, opts ...grpc.CallOption) (*AgentConfigResponse, error)
	DeleteAgent(ctx context.Context, in *AgentDeleteRequest, opts ...grpc.CallOption) (*AgentConfigResponse, error)
	GetAgent(ctx context.Context, in *AgentGetRequest, opts ...grpc.CallOption) (*AgentConfigResponse, error)
	ListAgents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentListResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, AgentService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_StreamChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamChatClient = grpc.ServerStreamingClient[ChatStreamResponse]

func (c *agentServiceClient) ListAgentTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentTypesResponse)
	err := c.cc.Invoke(ctx, AgentService_ListAgentTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListTools(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AddMCPService(ctx context.Context, in *MCPServiceRequest, opts ...grpc.CallOption) (*MCPServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPServiceResponse)
	err := c.cc.Invoke(ctx, AgentService_AddMCPService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RemoveMCPService(ctx context.Context, in *MCPServiceRequest, opts ...grpc.CallOption) (*MCPServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPServiceResponse)
	err := c.cc.Invoke(ctx, AgentService_RemoveMCPService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListMCPServices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MCPServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPServicesResponse)
	err := c.cc.Invoke(ctx, AgentService_ListMCPServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListMCPServicesWithId(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MCPServicesWithIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPServicesWithIdResponse)
	err := c.cc.Invoke(ctx, AgentService_ListMCPServicesWithId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetMCPServiceTools(ctx context.Context, in *MCPServiceToolsRequest, opts ...grpc.CallOption) (*MCPServiceToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPServiceToolsResponse)
	err := c.cc.Invoke(ctx, AgentService_GetMCPServiceTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateAgent(ctx context.Context, in *AgentConfigRequest, opts ...grpc.CallOption) (*AgentConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_CreateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateAgent(ctx context.Context, in *AgentConfigRequest, opts ...grpc.CallOption) (*AgentConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_UpdateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteAgent(ctx context.Context, in *AgentDeleteRequest, opts ...grpc.CallOption) (*AgentConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_DeleteAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgent(ctx context.Context, in *AgentGetRequest, opts ...grpc.CallOption) (*AgentConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListAgents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentListResponse)
	err := c.cc.Invoke(ctx, AgentService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// Agent服务定义（Kratos风格）
type AgentServiceServer interface {
	// 单次对话请求
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	// 流式对话请求
	StreamChat(*ChatRequest, grpc.ServerStreamingServer[ChatStreamResponse]) error
	// 获取可用的Agent类型
	ListAgentTypes(context.Context, *Empty) (*AgentTypesResponse, error)
	// 获取可用的工具列表
	ListTools(context.Context, *Empty) (*ToolsResponse, error)
	// MCP 服务管理
	AddMCPService(context.Context, *MCPServiceRequest) (*MCPServiceResponse, error)
	RemoveMCPService(context.Context, *MCPServiceRequest) (*MCPServiceResponse, error)
	ListMCPServices(context.Context, *Empty) (*MCPServicesResponse, error)
	ListMCPServicesWithId(context.Context, *Empty) (*MCPServicesWithIdResponse, error)
	GetMCPServiceTools(context.Context, *MCPServiceToolsRequest) (*MCPServiceToolsResponse, error)
	// Agent 管理
	CreateAgent(context.Context, *AgentConfigRequest) (*AgentConfigResponse, error)
	UpdateAgent(context.Context, *AgentConfigRequest) (*AgentConfigResponse, error)
	DeleteAgent(context.Context, *AgentDeleteRequest) (*AgentConfigResponse, error)
	GetAgent(context.Context, *AgentGetRequest) (*AgentConfigResponse, error)
	ListAgents(context.Context, *Empty) (*AgentListResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAgentServiceServer) StreamChat(*ChatRequest, grpc.ServerStreamingServer[ChatStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamChat not implemented")
}
func (UnimplementedAgentServiceServer) ListAgentTypes(context.Context, *Empty) (*AgentTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgentTypes not implemented")
}
func (UnimplementedAgentServiceServer) ListTools(context.Context, *Empty) (*ToolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedAgentServiceServer) AddMCPService(context.Context, *MCPServiceRequest) (*MCPServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMCPService not implemented")
}
func (UnimplementedAgentServiceServer) RemoveMCPService(context.Context, *MCPServiceRequest) (*MCPServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMCPService not implemented")
}
func (UnimplementedAgentServiceServer) ListMCPServices(context.Context, *Empty) (*MCPServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMCPServices not implemented")
}
func (UnimplementedAgentServiceServer) ListMCPServicesWithId(context.Context, *Empty) (*MCPServicesWithIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMCPServicesWithId not implemented")
}
func (UnimplementedAgentServiceServer) GetMCPServiceTools(context.Context, *MCPServiceToolsRequest) (*MCPServiceToolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMCPServiceTools not implemented")
}
func (UnimplementedAgentServiceServer) CreateAgent(context.Context, *AgentConfigRequest) (*AgentConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgent not implemented")
}
func (UnimplementedAgentServiceServer) UpdateAgent(context.Context, *AgentConfigRequest) (*AgentConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (UnimplementedAgentServiceServer) DeleteAgent(context.Context, *AgentDeleteRequest) (*AgentConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAgent not implemented")
}
func (UnimplementedAgentServiceServer) GetAgent(context.Context, *AgentGetRequest) (*AgentConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedAgentServiceServer) ListAgents(context.Context, *Empty) (*AgentListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamChat(m, &grpc.GenericServerStream[ChatRequest, ChatStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamChatServer = grpc.ServerStreamingServer[ChatStreamResponse]

func _AgentService_ListAgentTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgentTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAgentTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgentTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListTools(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AddMCPService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MCPServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AddMCPService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AddMCPService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AddMCPService(ctx, req.(*MCPServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RemoveMCPService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MCPServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RemoveMCPService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RemoveMCPService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RemoveMCPService(ctx, req.(*MCPServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListMCPServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListMCPServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListMCPServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListMCPServices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListMCPServicesWithId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListMCPServicesWithId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListMCPServicesWithId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListMCPServicesWithId(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetMCPServiceTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MCPServiceToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetMCPServiceTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetMCPServiceTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetMCPServiceTools(ctx, req.(*MCPServiceToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateAgent(ctx, req.(*AgentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UpdateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateAgent(ctx, req.(*AgentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeleteAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteAgent(ctx, req.(*AgentDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgent(ctx, req.(*AgentGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgents(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.agent.service.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _AgentService_Chat_Handler,
		},
		{
			MethodName: "ListAgentTypes",
			Handler:    _AgentService_ListAgentTypes_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _AgentService_ListTools_Handler,
		},
		{
			MethodName: "AddMCPService",
			Handler:    _AgentService_AddMCPService_Handler,
		},
		{
			MethodName: "RemoveMCPService",
			Handler:    _AgentService_RemoveMCPService_Handler,
		},
		{
			MethodName: "ListMCPServices",
			Handler:    _AgentService_ListMCPServices_Handler,
		},
		{
			MethodName: "ListMCPServicesWithId",
			Handler:    _AgentService_ListMCPServicesWithId_Handler,
		},
		{
			MethodName: "GetMCPServiceTools",
			Handler:    _AgentService_GetMCPServiceTools_Handler,
		},
		{
			MethodName: "CreateAgent",
			Handler:    _AgentService_CreateAgent_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _AgentService_UpdateAgent_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _AgentService_DeleteAgent_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _AgentService_GetAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _AgentService_ListAgents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChat",
			Handler:       _AgentService_StreamChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent/service/v1/agent_service.proto",
}
