// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/agent/service/v1/knowledge.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 知识库请求
type KnowledgeBaseRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                         // 知识库ID（更新时需要）
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                      // 知识库名称
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                        // 知识库描述
	Tags              []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`                                                      // 标签列表
	EmbeddingModel    string                 `protobuf:"bytes,5,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`            // 嵌入模型
	ChunkSize         int32                  `protobuf:"varint,6,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`                          // 分块大小
	ChunkOverlap      int32                  `protobuf:"varint,7,opt,name=chunk_overlap,json=chunkOverlap,proto3" json:"chunk_overlap,omitempty"`                 // 分块重叠大小
	VectorStoreType   string                 `protobuf:"bytes,8,opt,name=vector_store_type,json=vectorStoreType,proto3" json:"vector_store_type,omitempty"`       // 向量存储类型
	VectorStoreConfig string                 `protobuf:"bytes,9,opt,name=vector_store_config,json=vectorStoreConfig,proto3" json:"vector_store_config,omitempty"` // 向量存储配置（JSON字符串）
	IsActive          bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`                            // 是否激活
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KnowledgeBaseRequest) Reset() {
	*x = KnowledgeBaseRequest{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBaseRequest) ProtoMessage() {}

func (x *KnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*KnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *KnowledgeBaseRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KnowledgeBaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KnowledgeBaseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KnowledgeBaseRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *KnowledgeBaseRequest) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *KnowledgeBaseRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *KnowledgeBaseRequest) GetChunkOverlap() int32 {
	if x != nil {
		return x.ChunkOverlap
	}
	return 0
}

func (x *KnowledgeBaseRequest) GetVectorStoreType() string {
	if x != nil {
		return x.VectorStoreType
	}
	return ""
}

func (x *KnowledgeBaseRequest) GetVectorStoreConfig() string {
	if x != nil {
		return x.VectorStoreConfig
	}
	return ""
}

func (x *KnowledgeBaseRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// 知识库响应
type KnowledgeBaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *BaseResponse          `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	KnowledgeBase *KnowledgeBaseInfo     `protobuf:"bytes,2,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeBaseResponse) Reset() {
	*x = KnowledgeBaseResponse{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBaseResponse) ProtoMessage() {}

func (x *KnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*KnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *KnowledgeBaseResponse) GetRet() *BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *KnowledgeBaseResponse) GetKnowledgeBase() *KnowledgeBaseInfo {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

// 知识库信息
type KnowledgeBaseInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags              []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"` // 标签列表
	EmbeddingModel    string                 `protobuf:"bytes,5,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	ChunkSize         int32                  `protobuf:"varint,6,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChunkOverlap      int32                  `protobuf:"varint,7,opt,name=chunk_overlap,json=chunkOverlap,proto3" json:"chunk_overlap,omitempty"`
	VectorStoreType   string                 `protobuf:"bytes,8,opt,name=vector_store_type,json=vectorStoreType,proto3" json:"vector_store_type,omitempty"`
	VectorStoreConfig string                 `protobuf:"bytes,9,opt,name=vector_store_config,json=vectorStoreConfig,proto3" json:"vector_store_config,omitempty"`
	IsActive          bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DocumentCount     int32                  `protobuf:"varint,11,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"` // 文档数量
	CreatedAt         string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KnowledgeBaseInfo) Reset() {
	*x = KnowledgeBaseInfo{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBaseInfo) ProtoMessage() {}

func (x *KnowledgeBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBaseInfo.ProtoReflect.Descriptor instead.
func (*KnowledgeBaseInfo) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *KnowledgeBaseInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KnowledgeBaseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KnowledgeBaseInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KnowledgeBaseInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *KnowledgeBaseInfo) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *KnowledgeBaseInfo) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *KnowledgeBaseInfo) GetChunkOverlap() int32 {
	if x != nil {
		return x.ChunkOverlap
	}
	return 0
}

func (x *KnowledgeBaseInfo) GetVectorStoreType() string {
	if x != nil {
		return x.VectorStoreType
	}
	return ""
}

func (x *KnowledgeBaseInfo) GetVectorStoreConfig() string {
	if x != nil {
		return x.VectorStoreConfig
	}
	return ""
}

func (x *KnowledgeBaseInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *KnowledgeBaseInfo) GetDocumentCount() int32 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *KnowledgeBaseInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *KnowledgeBaseInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 知识库删除请求
type KnowledgeBaseDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeBaseDeleteRequest) Reset() {
	*x = KnowledgeBaseDeleteRequest{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeBaseDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBaseDeleteRequest) ProtoMessage() {}

func (x *KnowledgeBaseDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBaseDeleteRequest.ProtoReflect.Descriptor instead.
func (*KnowledgeBaseDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *KnowledgeBaseDeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 知识库获取请求
type KnowledgeBaseGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeBaseGetRequest) Reset() {
	*x = KnowledgeBaseGetRequest{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeBaseGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBaseGetRequest) ProtoMessage() {}

func (x *KnowledgeBaseGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBaseGetRequest.ProtoReflect.Descriptor instead.
func (*KnowledgeBaseGetRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *KnowledgeBaseGetRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 知识库列表请求
type KnowledgeBaseListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"` // 可选：搜索关键词（按名称）
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`     // 可选：标签筛选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeBaseListRequest) Reset() {
	*x = KnowledgeBaseListRequest{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeBaseListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBaseListRequest) ProtoMessage() {}

func (x *KnowledgeBaseListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBaseListRequest.ProtoReflect.Descriptor instead.
func (*KnowledgeBaseListRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *KnowledgeBaseListRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *KnowledgeBaseListRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 知识库列表响应
type KnowledgeBaseListResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ret            *BaseResponse          `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	KnowledgeBases []*KnowledgeBaseInfo   `protobuf:"bytes,2,rep,name=knowledge_bases,json=knowledgeBases,proto3" json:"knowledge_bases,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KnowledgeBaseListResponse) Reset() {
	*x = KnowledgeBaseListResponse{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeBaseListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBaseListResponse) ProtoMessage() {}

func (x *KnowledgeBaseListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBaseListResponse.ProtoReflect.Descriptor instead.
func (*KnowledgeBaseListResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *KnowledgeBaseListResponse) GetRet() *BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *KnowledgeBaseListResponse) GetKnowledgeBases() []*KnowledgeBaseInfo {
	if x != nil {
		return x.KnowledgeBases
	}
	return nil
}

// 文档上传请求（流式）
type DocumentUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*DocumentUploadRequest_Metadata
	//	*DocumentUploadRequest_Chunk
	Data          isDocumentUploadRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentUploadRequest) Reset() {
	*x = DocumentUploadRequest{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentUploadRequest) ProtoMessage() {}

func (x *DocumentUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentUploadRequest.ProtoReflect.Descriptor instead.
func (*DocumentUploadRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *DocumentUploadRequest) GetData() isDocumentUploadRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DocumentUploadRequest) GetMetadata() *DocumentUploadMetadata {
	if x != nil {
		if x, ok := x.Data.(*DocumentUploadRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *DocumentUploadRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*DocumentUploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isDocumentUploadRequest_Data interface {
	isDocumentUploadRequest_Data()
}

type DocumentUploadRequest_Metadata struct {
	Metadata *DocumentUploadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // 第一次发送：元数据
}

type DocumentUploadRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // 后续发送：文件块
}

func (*DocumentUploadRequest_Metadata) isDocumentUploadRequest_Data() {}

func (*DocumentUploadRequest_Chunk) isDocumentUploadRequest_Data() {}

type DocumentUploadMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeBaseId int32                  `protobuf:"varint,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"` // 知识库ID
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                 // 文档名称
	FileType        string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`                         // 文件类型
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocumentUploadMetadata) Reset() {
	*x = DocumentUploadMetadata{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentUploadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentUploadMetadata) ProtoMessage() {}

func (x *DocumentUploadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentUploadMetadata.ProtoReflect.Descriptor instead.
func (*DocumentUploadMetadata) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *DocumentUploadMetadata) GetKnowledgeBaseId() int32 {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return 0
}

func (x *DocumentUploadMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DocumentUploadMetadata) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

// 文档上传响应
type DocumentUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *BaseResponse          `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Document      *DocumentInfo          `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"` // 处理后的块数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentUploadResponse) Reset() {
	*x = DocumentUploadResponse{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentUploadResponse) ProtoMessage() {}

func (x *DocumentUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentUploadResponse.ProtoReflect.Descriptor instead.
func (*DocumentUploadResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *DocumentUploadResponse) GetRet() *BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *DocumentUploadResponse) GetDocument() *DocumentInfo {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *DocumentUploadResponse) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

// 文档删除请求
type DocumentDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentDeleteRequest) Reset() {
	*x = DocumentDeleteRequest{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentDeleteRequest) ProtoMessage() {}

func (x *DocumentDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentDeleteRequest.ProtoReflect.Descriptor instead.
func (*DocumentDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *DocumentDeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 文档获取请求
type DocumentGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentGetRequest) Reset() {
	*x = DocumentGetRequest{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentGetRequest) ProtoMessage() {}

func (x *DocumentGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentGetRequest.ProtoReflect.Descriptor instead.
func (*DocumentGetRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{11}
}

func (x *DocumentGetRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 文档列表请求
type DocumentListRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeBaseId int32                  `protobuf:"varint,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"` // 知识库ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocumentListRequest) Reset() {
	*x = DocumentListRequest{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentListRequest) ProtoMessage() {}

func (x *DocumentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentListRequest.ProtoReflect.Descriptor instead.
func (*DocumentListRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{12}
}

func (x *DocumentListRequest) GetKnowledgeBaseId() int32 {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return 0
}

// 文档响应
type DocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *BaseResponse          `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Document      *DocumentInfo          `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentResponse) Reset() {
	*x = DocumentResponse{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentResponse) ProtoMessage() {}

func (x *DocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentResponse.ProtoReflect.Descriptor instead.
func (*DocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{13}
}

func (x *DocumentResponse) GetRet() *BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *DocumentResponse) GetDocument() *DocumentInfo {
	if x != nil {
		return x.Document
	}
	return nil
}

// 文档列表响应
type DocumentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *BaseResponse          `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Documents     []*DocumentInfo        `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentListResponse) Reset() {
	*x = DocumentListResponse{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentListResponse) ProtoMessage() {}

func (x *DocumentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentListResponse.ProtoReflect.Descriptor instead.
func (*DocumentListResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{14}
}

func (x *DocumentListResponse) GetRet() *BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *DocumentListResponse) GetDocuments() []*DocumentInfo {
	if x != nil {
		return x.Documents
	}
	return nil
}

// 文档信息
type DocumentInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	KnowledgeBaseId int32                  `protobuf:"varint,2,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FilePath        string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSize        int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileType        string                 `protobuf:"bytes,6,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // pending, processing, completed, failed
	ChunkCount      int32                  `protobuf:"varint,8,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	ProcessedAt     string                 `protobuf:"bytes,9,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`     // 处理完成时间
	ErrorMessage    string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 错误信息
	Metadata        string                 `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`                             // 元数据（JSON字符串）
	CreatedAt       string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocumentInfo) Reset() {
	*x = DocumentInfo{}
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentInfo) ProtoMessage() {}

func (x *DocumentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_service_v1_knowledge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentInfo.ProtoReflect.Descriptor instead.
func (*DocumentInfo) Descriptor() ([]byte, []int) {
	return file_api_agent_service_v1_knowledge_proto_rawDescGZIP(), []int{15}
}

func (x *DocumentInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DocumentInfo) GetKnowledgeBaseId() int32 {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return 0
}

func (x *DocumentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DocumentInfo) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DocumentInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *DocumentInfo) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *DocumentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DocumentInfo) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *DocumentInfo) GetProcessedAt() string {
	if x != nil {
		return x.ProcessedAt
	}
	return ""
}

func (x *DocumentInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DocumentInfo) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *DocumentInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DocumentInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_agent_service_v1_knowledge_proto protoreflect.FileDescriptor

const file_api_agent_service_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"$api/agent/service/v1/knowledge.proto\x12\x14api.agent.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a!api/agent/service/v1/common.proto\"\xd6\x02\n" +
	"\x14KnowledgeBaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12'\n" +
	"\x0fembedding_model\x18\x05 \x01(\tR\x0eembeddingModel\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x06 \x01(\x05R\tchunkSize\x12#\n" +
	"\rchunk_overlap\x18\a \x01(\x05R\fchunkOverlap\x12*\n" +
	"\x11vector_store_type\x18\b \x01(\tR\x0fvectorStoreType\x12.\n" +
	"\x13vector_store_config\x18\t \x01(\tR\x11vectorStoreConfig\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\"\x9d\x01\n" +
	"\x15KnowledgeBaseResponse\x124\n" +
	"\x03ret\x18\x01 \x01(\v2\".api.agent.service.v1.BaseResponseR\x03ret\x12N\n" +
	"\x0eknowledge_base\x18\x02 \x01(\v2'.api.agent.service.v1.KnowledgeBaseInfoR\rknowledgeBase\"\xb8\x03\n" +
	"\x11KnowledgeBaseInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12'\n" +
	"\x0fembedding_model\x18\x05 \x01(\tR\x0eembeddingModel\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x06 \x01(\x05R\tchunkSize\x12#\n" +
	"\rchunk_overlap\x18\a \x01(\x05R\fchunkOverlap\x12*\n" +
	"\x11vector_store_type\x18\b \x01(\tR\x0fvectorStoreType\x12.\n" +
	"\x13vector_store_config\x18\t \x01(\tR\x11vectorStoreConfig\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12%\n" +
	"\x0edocument_count\x18\v \x01(\x05R\rdocumentCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\",\n" +
	"\x1aKnowledgeBaseDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\")\n" +
	"\x17KnowledgeBaseGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"F\n" +
	"\x18KnowledgeBaseListRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"\xa3\x01\n" +
	"\x19KnowledgeBaseListResponse\x124\n" +
	"\x03ret\x18\x01 \x01(\v2\".api.agent.service.v1.BaseResponseR\x03ret\x12P\n" +
	"\x0fknowledge_bases\x18\x02 \x03(\v2'.api.agent.service.v1.KnowledgeBaseInfoR\x0eknowledgeBases\"\x83\x01\n" +
	"\x15DocumentUploadRequest\x12J\n" +
	"\bmetadata\x18\x01 \x01(\v2,.api.agent.service.v1.DocumentUploadMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"u\n" +
	"\x16DocumentUploadMetadata\x12*\n" +
	"\x11knowledge_base_id\x18\x01 \x01(\x05R\x0fknowledgeBaseId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\"\xaf\x01\n" +
	"\x16DocumentUploadResponse\x124\n" +
	"\x03ret\x18\x01 \x01(\v2\".api.agent.service.v1.BaseResponseR\x03ret\x12>\n" +
	"\bdocument\x18\x02 \x01(\v2\".api.agent.service.v1.DocumentInfoR\bdocument\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\"'\n" +
	"\x15DocumentDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"$\n" +
	"\x12DocumentGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"A\n" +
	"\x13DocumentListRequest\x12*\n" +
	"\x11knowledge_base_id\x18\x01 \x01(\x05R\x0fknowledgeBaseId\"\x88\x01\n" +
	"\x10DocumentResponse\x124\n" +
	"\x03ret\x18\x01 \x01(\v2\".api.agent.service.v1.BaseResponseR\x03ret\x12>\n" +
	"\bdocument\x18\x02 \x01(\v2\".api.agent.service.v1.DocumentInfoR\bdocument\"\x8e\x01\n" +
	"\x14DocumentListResponse\x124\n" +
	"\x03ret\x18\x01 \x01(\v2\".api.agent.service.v1.BaseResponseR\x03ret\x12@\n" +
	"\tdocuments\x18\x02 \x03(\v2\".api.agent.service.v1.DocumentInfoR\tdocuments\"\x90\x03\n" +
	"\fDocumentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12*\n" +
	"\x11knowledge_base_id\x18\x02 \x01(\x05R\x0fknowledgeBaseId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tfile_type\x18\x06 \x01(\tR\bfileType\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vchunk_count\x18\b \x01(\x05R\n" +
	"chunkCount\x12!\n" +
	"\fprocessed_at\x18\t \x01(\tR\vprocessedAt\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x12\x1a\n" +
	"\bmetadata\x18\v \x01(\tR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt2\xa7\t\n" +
	"\x10KnowledgeService\x12\x8f\x01\n" +
	"\x13CreateKnowledgeBase\x12*.api.agent.service.v1.KnowledgeBaseRequest\x1a+.api.agent.service.v1.KnowledgeBaseResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/knowledge-bases\x12\x94\x01\n" +
	"\x13UpdateKnowledgeBase\x12*.api.agent.service.v1.KnowledgeBaseRequest\x1a+.api.agent.service.v1.KnowledgeBaseResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/knowledge-bases/{id}\x12\x97\x01\n" +
	"\x13DeleteKnowledgeBase\x120.api.agent.service.v1.KnowledgeBaseDeleteRequest\x1a+.api.agent.service.v1.KnowledgeBaseResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/api/knowledge-bases/{id}\x12\x91\x01\n" +
	"\x10GetKnowledgeBase\x12-.api.agent.service.v1.KnowledgeBaseGetRequest\x1a+.api.agent.service.v1.KnowledgeBaseResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/knowledge-bases/{id}\x12\x93\x01\n" +
	"\x12ListKnowledgeBases\x12..api.agent.service.v1.KnowledgeBaseListRequest\x1a/.api.agent.service.v1.KnowledgeBaseListResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/knowledge-bases\x12\x82\x01\n" +
	"\x0eDeleteDocument\x12+.api.agent.service.v1.DocumentDeleteRequest\x1a&.api.agent.service.v1.DocumentResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/documents/{id}\x12|\n" +
	"\vGetDocument\x12(.api.agent.service.v1.DocumentGetRequest\x1a&.api.agent.service.v1.DocumentResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/documents/{id}\x12\xa2\x01\n" +
	"\rListDocuments\x12).api.agent.service.v1.DocumentListRequest\x1a*.api.agent.service.v1.DocumentListResponse\":\x82\xd3\xe4\x93\x024\x122/api/knowledge-bases/{knowledge_base_id}/documentsB#Z!jas-agent/api/agent/service/v1;v1b\x06proto3"

var (
	file_api_agent_service_v1_knowledge_proto_rawDescOnce sync.Once
	file_api_agent_service_v1_knowledge_proto_rawDescData []byte
)

func file_api_agent_service_v1_knowledge_proto_rawDescGZIP() []byte {
	file_api_agent_service_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_api_agent_service_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_service_v1_knowledge_proto_rawDesc), len(file_api_agent_service_v1_knowledge_proto_rawDesc)))
	})
	return file_api_agent_service_v1_knowledge_proto_rawDescData
}

var file_api_agent_service_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_agent_service_v1_knowledge_proto_goTypes = []any{
	(*KnowledgeBaseRequest)(nil),       // 0: api.agent.service.v1.KnowledgeBaseRequest
	(*KnowledgeBaseResponse)(nil),      // 1: api.agent.service.v1.KnowledgeBaseResponse
	(*KnowledgeBaseInfo)(nil),          // 2: api.agent.service.v1.KnowledgeBaseInfo
	(*KnowledgeBaseDeleteRequest)(nil), // 3: api.agent.service.v1.KnowledgeBaseDeleteRequest
	(*KnowledgeBaseGetRequest)(nil),    // 4: api.agent.service.v1.KnowledgeBaseGetRequest
	(*KnowledgeBaseListRequest)(nil),   // 5: api.agent.service.v1.KnowledgeBaseListRequest
	(*KnowledgeBaseListResponse)(nil),  // 6: api.agent.service.v1.KnowledgeBaseListResponse
	(*DocumentUploadRequest)(nil),      // 7: api.agent.service.v1.DocumentUploadRequest
	(*DocumentUploadMetadata)(nil),     // 8: api.agent.service.v1.DocumentUploadMetadata
	(*DocumentUploadResponse)(nil),     // 9: api.agent.service.v1.DocumentUploadResponse
	(*DocumentDeleteRequest)(nil),      // 10: api.agent.service.v1.DocumentDeleteRequest
	(*DocumentGetRequest)(nil),         // 11: api.agent.service.v1.DocumentGetRequest
	(*DocumentListRequest)(nil),        // 12: api.agent.service.v1.DocumentListRequest
	(*DocumentResponse)(nil),           // 13: api.agent.service.v1.DocumentResponse
	(*DocumentListResponse)(nil),       // 14: api.agent.service.v1.DocumentListResponse
	(*DocumentInfo)(nil),               // 15: api.agent.service.v1.DocumentInfo
	(*BaseResponse)(nil),               // 16: api.agent.service.v1.BaseResponse
}
var file_api_agent_service_v1_knowledge_proto_depIdxs = []int32{
	16, // 0: api.agent.service.v1.KnowledgeBaseResponse.ret:type_name -> api.agent.service.v1.BaseResponse
	2,  // 1: api.agent.service.v1.KnowledgeBaseResponse.knowledge_base:type_name -> api.agent.service.v1.KnowledgeBaseInfo
	16, // 2: api.agent.service.v1.KnowledgeBaseListResponse.ret:type_name -> api.agent.service.v1.BaseResponse
	2,  // 3: api.agent.service.v1.KnowledgeBaseListResponse.knowledge_bases:type_name -> api.agent.service.v1.KnowledgeBaseInfo
	8,  // 4: api.agent.service.v1.DocumentUploadRequest.metadata:type_name -> api.agent.service.v1.DocumentUploadMetadata
	16, // 5: api.agent.service.v1.DocumentUploadResponse.ret:type_name -> api.agent.service.v1.BaseResponse
	15, // 6: api.agent.service.v1.DocumentUploadResponse.document:type_name -> api.agent.service.v1.DocumentInfo
	16, // 7: api.agent.service.v1.DocumentResponse.ret:type_name -> api.agent.service.v1.BaseResponse
	15, // 8: api.agent.service.v1.DocumentResponse.document:type_name -> api.agent.service.v1.DocumentInfo
	16, // 9: api.agent.service.v1.DocumentListResponse.ret:type_name -> api.agent.service.v1.BaseResponse
	15, // 10: api.agent.service.v1.DocumentListResponse.documents:type_name -> api.agent.service.v1.DocumentInfo
	0,  // 11: api.agent.service.v1.KnowledgeService.CreateKnowledgeBase:input_type -> api.agent.service.v1.KnowledgeBaseRequest
	0,  // 12: api.agent.service.v1.KnowledgeService.UpdateKnowledgeBase:input_type -> api.agent.service.v1.KnowledgeBaseRequest
	3,  // 13: api.agent.service.v1.KnowledgeService.DeleteKnowledgeBase:input_type -> api.agent.service.v1.KnowledgeBaseDeleteRequest
	4,  // 14: api.agent.service.v1.KnowledgeService.GetKnowledgeBase:input_type -> api.agent.service.v1.KnowledgeBaseGetRequest
	5,  // 15: api.agent.service.v1.KnowledgeService.ListKnowledgeBases:input_type -> api.agent.service.v1.KnowledgeBaseListRequest
	10, // 16: api.agent.service.v1.KnowledgeService.DeleteDocument:input_type -> api.agent.service.v1.DocumentDeleteRequest
	11, // 17: api.agent.service.v1.KnowledgeService.GetDocument:input_type -> api.agent.service.v1.DocumentGetRequest
	12, // 18: api.agent.service.v1.KnowledgeService.ListDocuments:input_type -> api.agent.service.v1.DocumentListRequest
	1,  // 19: api.agent.service.v1.KnowledgeService.CreateKnowledgeBase:output_type -> api.agent.service.v1.KnowledgeBaseResponse
	1,  // 20: api.agent.service.v1.KnowledgeService.UpdateKnowledgeBase:output_type -> api.agent.service.v1.KnowledgeBaseResponse
	1,  // 21: api.agent.service.v1.KnowledgeService.DeleteKnowledgeBase:output_type -> api.agent.service.v1.KnowledgeBaseResponse
	1,  // 22: api.agent.service.v1.KnowledgeService.GetKnowledgeBase:output_type -> api.agent.service.v1.KnowledgeBaseResponse
	6,  // 23: api.agent.service.v1.KnowledgeService.ListKnowledgeBases:output_type -> api.agent.service.v1.KnowledgeBaseListResponse
	13, // 24: api.agent.service.v1.KnowledgeService.DeleteDocument:output_type -> api.agent.service.v1.DocumentResponse
	13, // 25: api.agent.service.v1.KnowledgeService.GetDocument:output_type -> api.agent.service.v1.DocumentResponse
	14, // 26: api.agent.service.v1.KnowledgeService.ListDocuments:output_type -> api.agent.service.v1.DocumentListResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_agent_service_v1_knowledge_proto_init() }
func file_api_agent_service_v1_knowledge_proto_init() {
	if File_api_agent_service_v1_knowledge_proto != nil {
		return
	}
	file_api_agent_service_v1_common_proto_init()
	file_api_agent_service_v1_knowledge_proto_msgTypes[7].OneofWrappers = []any{
		(*DocumentUploadRequest_Metadata)(nil),
		(*DocumentUploadRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_service_v1_knowledge_proto_rawDesc), len(file_api_agent_service_v1_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_agent_service_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_api_agent_service_v1_knowledge_proto_depIdxs,
		MessageInfos:      file_api_agent_service_v1_knowledge_proto_msgTypes,
	}.Build()
	File_api_agent_service_v1_knowledge_proto = out.File
	file_api_agent_service_v1_knowledge_proto_goTypes = nil
	file_api_agent_service_v1_knowledge_proto_depIdxs = nil
}
