// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.30.2
// source: api/agent/service/v1/knowledge.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationKnowledgeServiceCreateKnowledgeBase = "/api.agent.service.v1.KnowledgeService/CreateKnowledgeBase"
const OperationKnowledgeServiceDeleteDocument = "/api.agent.service.v1.KnowledgeService/DeleteDocument"
const OperationKnowledgeServiceDeleteKnowledgeBase = "/api.agent.service.v1.KnowledgeService/DeleteKnowledgeBase"
const OperationKnowledgeServiceGetDocument = "/api.agent.service.v1.KnowledgeService/GetDocument"
const OperationKnowledgeServiceGetKnowledgeBase = "/api.agent.service.v1.KnowledgeService/GetKnowledgeBase"
const OperationKnowledgeServiceListDocuments = "/api.agent.service.v1.KnowledgeService/ListDocuments"
const OperationKnowledgeServiceListKnowledgeBases = "/api.agent.service.v1.KnowledgeService/ListKnowledgeBases"
const OperationKnowledgeServiceUpdateKnowledgeBase = "/api.agent.service.v1.KnowledgeService/UpdateKnowledgeBase"

type KnowledgeServiceHTTPServer interface {
	// CreateKnowledgeBase 知识库管理
	CreateKnowledgeBase(context.Context, *KnowledgeBaseRequest) (*KnowledgeBaseResponse, error)
	// DeleteDocument 文档管理（使用 HTTP multipart/form-data 上传）
	// 注意：由于 HTTP 网关限制，流式上传改为 HTTP POST multipart/form-data
	// 实际实现通过 HTTP handler 处理，不使用 gRPC 流式接口
	DeleteDocument(context.Context, *DocumentDeleteRequest) (*DocumentResponse, error)
	DeleteKnowledgeBase(context.Context, *KnowledgeBaseDeleteRequest) (*KnowledgeBaseResponse, error)
	GetDocument(context.Context, *DocumentGetRequest) (*DocumentResponse, error)
	GetKnowledgeBase(context.Context, *KnowledgeBaseGetRequest) (*KnowledgeBaseResponse, error)
	ListDocuments(context.Context, *DocumentListRequest) (*DocumentListResponse, error)
	ListKnowledgeBases(context.Context, *KnowledgeBaseListRequest) (*KnowledgeBaseListResponse, error)
	UpdateKnowledgeBase(context.Context, *KnowledgeBaseRequest) (*KnowledgeBaseResponse, error)
}

func RegisterKnowledgeServiceHTTPServer(s *http.Server, srv KnowledgeServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/knowledge-bases", _KnowledgeService_CreateKnowledgeBase0_HTTP_Handler(srv))
	r.PUT("/api/knowledge-bases/{id}", _KnowledgeService_UpdateKnowledgeBase0_HTTP_Handler(srv))
	r.DELETE("/api/knowledge-bases/{id}", _KnowledgeService_DeleteKnowledgeBase0_HTTP_Handler(srv))
	r.GET("/api/knowledge-bases/{id}", _KnowledgeService_GetKnowledgeBase0_HTTP_Handler(srv))
	r.GET("/api/knowledge-bases", _KnowledgeService_ListKnowledgeBases0_HTTP_Handler(srv))
	r.DELETE("/api/documents/{id}", _KnowledgeService_DeleteDocument0_HTTP_Handler(srv))
	r.GET("/api/documents/{id}", _KnowledgeService_GetDocument0_HTTP_Handler(srv))
	r.GET("/api/knowledge-bases/{knowledge_base_id}/documents", _KnowledgeService_ListDocuments0_HTTP_Handler(srv))
}

func _KnowledgeService_CreateKnowledgeBase0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in KnowledgeBaseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceCreateKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateKnowledgeBase(ctx, req.(*KnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KnowledgeBaseResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeService_UpdateKnowledgeBase0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in KnowledgeBaseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceUpdateKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateKnowledgeBase(ctx, req.(*KnowledgeBaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KnowledgeBaseResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeService_DeleteKnowledgeBase0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in KnowledgeBaseDeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceDeleteKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteKnowledgeBase(ctx, req.(*KnowledgeBaseDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KnowledgeBaseResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeService_GetKnowledgeBase0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in KnowledgeBaseGetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceGetKnowledgeBase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetKnowledgeBase(ctx, req.(*KnowledgeBaseGetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KnowledgeBaseResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeService_ListKnowledgeBases0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in KnowledgeBaseListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceListKnowledgeBases)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListKnowledgeBases(ctx, req.(*KnowledgeBaseListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KnowledgeBaseListResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeService_DeleteDocument0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DocumentDeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceDeleteDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDocument(ctx, req.(*DocumentDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DocumentResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeService_GetDocument0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DocumentGetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceGetDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDocument(ctx, req.(*DocumentGetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DocumentResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeService_ListDocuments0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DocumentListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceListDocuments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDocuments(ctx, req.(*DocumentListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DocumentListResponse)
		return ctx.Result(200, reply)
	}
}

type KnowledgeServiceHTTPClient interface {
	CreateKnowledgeBase(ctx context.Context, req *KnowledgeBaseRequest, opts ...http.CallOption) (rsp *KnowledgeBaseResponse, err error)
	DeleteDocument(ctx context.Context, req *DocumentDeleteRequest, opts ...http.CallOption) (rsp *DocumentResponse, err error)
	DeleteKnowledgeBase(ctx context.Context, req *KnowledgeBaseDeleteRequest, opts ...http.CallOption) (rsp *KnowledgeBaseResponse, err error)
	GetDocument(ctx context.Context, req *DocumentGetRequest, opts ...http.CallOption) (rsp *DocumentResponse, err error)
	GetKnowledgeBase(ctx context.Context, req *KnowledgeBaseGetRequest, opts ...http.CallOption) (rsp *KnowledgeBaseResponse, err error)
	ListDocuments(ctx context.Context, req *DocumentListRequest, opts ...http.CallOption) (rsp *DocumentListResponse, err error)
	ListKnowledgeBases(ctx context.Context, req *KnowledgeBaseListRequest, opts ...http.CallOption) (rsp *KnowledgeBaseListResponse, err error)
	UpdateKnowledgeBase(ctx context.Context, req *KnowledgeBaseRequest, opts ...http.CallOption) (rsp *KnowledgeBaseResponse, err error)
}

type KnowledgeServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewKnowledgeServiceHTTPClient(client *http.Client) KnowledgeServiceHTTPClient {
	return &KnowledgeServiceHTTPClientImpl{client}
}

func (c *KnowledgeServiceHTTPClientImpl) CreateKnowledgeBase(ctx context.Context, in *KnowledgeBaseRequest, opts ...http.CallOption) (*KnowledgeBaseResponse, error) {
	var out KnowledgeBaseResponse
	pattern := "/api/knowledge-bases"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeServiceCreateKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeServiceHTTPClientImpl) DeleteDocument(ctx context.Context, in *DocumentDeleteRequest, opts ...http.CallOption) (*DocumentResponse, error) {
	var out DocumentResponse
	pattern := "/api/documents/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeServiceDeleteDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeServiceHTTPClientImpl) DeleteKnowledgeBase(ctx context.Context, in *KnowledgeBaseDeleteRequest, opts ...http.CallOption) (*KnowledgeBaseResponse, error) {
	var out KnowledgeBaseResponse
	pattern := "/api/knowledge-bases/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeServiceDeleteKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeServiceHTTPClientImpl) GetDocument(ctx context.Context, in *DocumentGetRequest, opts ...http.CallOption) (*DocumentResponse, error) {
	var out DocumentResponse
	pattern := "/api/documents/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeServiceGetDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeServiceHTTPClientImpl) GetKnowledgeBase(ctx context.Context, in *KnowledgeBaseGetRequest, opts ...http.CallOption) (*KnowledgeBaseResponse, error) {
	var out KnowledgeBaseResponse
	pattern := "/api/knowledge-bases/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeServiceGetKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeServiceHTTPClientImpl) ListDocuments(ctx context.Context, in *DocumentListRequest, opts ...http.CallOption) (*DocumentListResponse, error) {
	var out DocumentListResponse
	pattern := "/api/knowledge-bases/{knowledge_base_id}/documents"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeServiceListDocuments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeServiceHTTPClientImpl) ListKnowledgeBases(ctx context.Context, in *KnowledgeBaseListRequest, opts ...http.CallOption) (*KnowledgeBaseListResponse, error) {
	var out KnowledgeBaseListResponse
	pattern := "/api/knowledge-bases"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeServiceListKnowledgeBases))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KnowledgeServiceHTTPClientImpl) UpdateKnowledgeBase(ctx context.Context, in *KnowledgeBaseRequest, opts ...http.CallOption) (*KnowledgeBaseResponse, error) {
	var out KnowledgeBaseResponse
	pattern := "/api/knowledge-bases/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeServiceUpdateKnowledgeBase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
