// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: api/agent/service/v1/knowledge.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeService_CreateKnowledgeBase_FullMethodName = "/api.agent.service.v1.KnowledgeService/CreateKnowledgeBase"
	KnowledgeService_UpdateKnowledgeBase_FullMethodName = "/api.agent.service.v1.KnowledgeService/UpdateKnowledgeBase"
	KnowledgeService_DeleteKnowledgeBase_FullMethodName = "/api.agent.service.v1.KnowledgeService/DeleteKnowledgeBase"
	KnowledgeService_GetKnowledgeBase_FullMethodName    = "/api.agent.service.v1.KnowledgeService/GetKnowledgeBase"
	KnowledgeService_ListKnowledgeBases_FullMethodName  = "/api.agent.service.v1.KnowledgeService/ListKnowledgeBases"
	KnowledgeService_DeleteDocument_FullMethodName      = "/api.agent.service.v1.KnowledgeService/DeleteDocument"
	KnowledgeService_GetDocument_FullMethodName         = "/api.agent.service.v1.KnowledgeService/GetDocument"
	KnowledgeService_ListDocuments_FullMethodName       = "/api.agent.service.v1.KnowledgeService/ListDocuments"
)

// KnowledgeServiceClient is the client API for KnowledgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent服务定义（Kratos风格）
type KnowledgeServiceClient interface {
	// 知识库管理
	CreateKnowledgeBase(ctx context.Context, in *KnowledgeBaseRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error)
	UpdateKnowledgeBase(ctx context.Context, in *KnowledgeBaseRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error)
	DeleteKnowledgeBase(ctx context.Context, in *KnowledgeBaseDeleteRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error)
	GetKnowledgeBase(ctx context.Context, in *KnowledgeBaseGetRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error)
	ListKnowledgeBases(ctx context.Context, in *KnowledgeBaseListRequest, opts ...grpc.CallOption) (*KnowledgeBaseListResponse, error)
	// 文档管理（使用 HTTP multipart/form-data 上传）
	// 注意：由于 HTTP 网关限制，流式上传改为 HTTP POST multipart/form-data
	// 实际实现通过 HTTP handler 处理，不使用 gRPC 流式接口
	DeleteDocument(ctx context.Context, in *DocumentDeleteRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	GetDocument(ctx context.Context, in *DocumentGetRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	ListDocuments(ctx context.Context, in *DocumentListRequest, opts ...grpc.CallOption) (*DocumentListResponse, error)
}

type knowledgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeServiceClient(cc grpc.ClientConnInterface) KnowledgeServiceClient {
	return &knowledgeServiceClient{cc}
}

func (c *knowledgeServiceClient) CreateKnowledgeBase(ctx context.Context, in *KnowledgeBaseRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeBaseResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_CreateKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) UpdateKnowledgeBase(ctx context.Context, in *KnowledgeBaseRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeBaseResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_UpdateKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) DeleteKnowledgeBase(ctx context.Context, in *KnowledgeBaseDeleteRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeBaseResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_DeleteKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) GetKnowledgeBase(ctx context.Context, in *KnowledgeBaseGetRequest, opts ...grpc.CallOption) (*KnowledgeBaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeBaseResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_GetKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) ListKnowledgeBases(ctx context.Context, in *KnowledgeBaseListRequest, opts ...grpc.CallOption) (*KnowledgeBaseListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeBaseListResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_ListKnowledgeBases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) DeleteDocument(ctx context.Context, in *DocumentDeleteRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) GetDocument(ctx context.Context, in *DocumentGetRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) ListDocuments(ctx context.Context, in *DocumentListRequest, opts ...grpc.CallOption) (*DocumentListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentListResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeServiceServer is the server API for KnowledgeService service.
// All implementations must embed UnimplementedKnowledgeServiceServer
// for forward compatibility.
//
// Agent服务定义（Kratos风格）
type KnowledgeServiceServer interface {
	// 知识库管理
	CreateKnowledgeBase(context.Context, *KnowledgeBaseRequest) (*KnowledgeBaseResponse, error)
	UpdateKnowledgeBase(context.Context, *KnowledgeBaseRequest) (*KnowledgeBaseResponse, error)
	DeleteKnowledgeBase(context.Context, *KnowledgeBaseDeleteRequest) (*KnowledgeBaseResponse, error)
	GetKnowledgeBase(context.Context, *KnowledgeBaseGetRequest) (*KnowledgeBaseResponse, error)
	ListKnowledgeBases(context.Context, *KnowledgeBaseListRequest) (*KnowledgeBaseListResponse, error)
	// 文档管理（使用 HTTP multipart/form-data 上传）
	// 注意：由于 HTTP 网关限制，流式上传改为 HTTP POST multipart/form-data
	// 实际实现通过 HTTP handler 处理，不使用 gRPC 流式接口
	DeleteDocument(context.Context, *DocumentDeleteRequest) (*DocumentResponse, error)
	GetDocument(context.Context, *DocumentGetRequest) (*DocumentResponse, error)
	ListDocuments(context.Context, *DocumentListRequest) (*DocumentListResponse, error)
	mustEmbedUnimplementedKnowledgeServiceServer()
}

// UnimplementedKnowledgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeServiceServer struct{}

func (UnimplementedKnowledgeServiceServer) CreateKnowledgeBase(context.Context, *KnowledgeBaseRequest) (*KnowledgeBaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKnowledgeBase not implemented")
}
func (UnimplementedKnowledgeServiceServer) UpdateKnowledgeBase(context.Context, *KnowledgeBaseRequest) (*KnowledgeBaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKnowledgeBase not implemented")
}
func (UnimplementedKnowledgeServiceServer) DeleteKnowledgeBase(context.Context, *KnowledgeBaseDeleteRequest) (*KnowledgeBaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKnowledgeBase not implemented")
}
func (UnimplementedKnowledgeServiceServer) GetKnowledgeBase(context.Context, *KnowledgeBaseGetRequest) (*KnowledgeBaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKnowledgeBase not implemented")
}
func (UnimplementedKnowledgeServiceServer) ListKnowledgeBases(context.Context, *KnowledgeBaseListRequest) (*KnowledgeBaseListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKnowledgeBases not implemented")
}
func (UnimplementedKnowledgeServiceServer) DeleteDocument(context.Context, *DocumentDeleteRequest) (*DocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedKnowledgeServiceServer) GetDocument(context.Context, *DocumentGetRequest) (*DocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedKnowledgeServiceServer) ListDocuments(context.Context, *DocumentListRequest) (*DocumentListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedKnowledgeServiceServer) mustEmbedUnimplementedKnowledgeServiceServer() {}
func (UnimplementedKnowledgeServiceServer) testEmbeddedByValue()                          {}

// UnsafeKnowledgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeServiceServer will
// result in compilation errors.
type UnsafeKnowledgeServiceServer interface {
	mustEmbedUnimplementedKnowledgeServiceServer()
}

func RegisterKnowledgeServiceServer(s grpc.ServiceRegistrar, srv KnowledgeServiceServer) {
	// If the following call pancis, it indicates UnimplementedKnowledgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeService_ServiceDesc, srv)
}

func _KnowledgeService_CreateKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).CreateKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_CreateKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).CreateKnowledgeBase(ctx, req.(*KnowledgeBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_UpdateKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).UpdateKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_UpdateKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).UpdateKnowledgeBase(ctx, req.(*KnowledgeBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_DeleteKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeBaseDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).DeleteKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_DeleteKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).DeleteKnowledgeBase(ctx, req.(*KnowledgeBaseDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_GetKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeBaseGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).GetKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_GetKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).GetKnowledgeBase(ctx, req.(*KnowledgeBaseGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_ListKnowledgeBases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeBaseListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).ListKnowledgeBases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_ListKnowledgeBases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).ListKnowledgeBases(ctx, req.(*KnowledgeBaseListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).DeleteDocument(ctx, req.(*DocumentDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).GetDocument(ctx, req.(*DocumentGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).ListDocuments(ctx, req.(*DocumentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeService_ServiceDesc is the grpc.ServiceDesc for KnowledgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.agent.service.v1.KnowledgeService",
	HandlerType: (*KnowledgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKnowledgeBase",
			Handler:    _KnowledgeService_CreateKnowledgeBase_Handler,
		},
		{
			MethodName: "UpdateKnowledgeBase",
			Handler:    _KnowledgeService_UpdateKnowledgeBase_Handler,
		},
		{
			MethodName: "DeleteKnowledgeBase",
			Handler:    _KnowledgeService_DeleteKnowledgeBase_Handler,
		},
		{
			MethodName: "GetKnowledgeBase",
			Handler:    _KnowledgeService_GetKnowledgeBase_Handler,
		},
		{
			MethodName: "ListKnowledgeBases",
			Handler:    _KnowledgeService_ListKnowledgeBases_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _KnowledgeService_DeleteDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _KnowledgeService_GetDocument_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _KnowledgeService_ListDocuments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/agent/service/v1/knowledge.proto",
}
