// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/proto/agent_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent类型枚举
type AgentType int32

const (
	AgentType_REACT AgentType = 0 // ReAct Agent
	AgentType_CHAIN AgentType = 1 // Chain Agent
	AgentType_PLAN  AgentType = 2 // Plan Agent
	AgentType_SQL   AgentType = 3 // SQL Agent
)

// Enum value maps for AgentType.
var (
	AgentType_name = map[int32]string{
		0: "REACT",
		1: "CHAIN",
		2: "PLAN",
		3: "SQL",
	}
	AgentType_value = map[string]int32{
		"REACT": 0,
		"CHAIN": 1,
		"PLAN":  2,
		"SQL":   3,
	}
)

func (x AgentType) Enum() *AgentType {
	p := new(AgentType)
	*p = x
	return p
}

func (x AgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_agent_service_proto_enumTypes[0].Descriptor()
}

func (AgentType) Type() protoreflect.EnumType {
	return &file_api_proto_agent_service_proto_enumTypes[0]
}

func (x AgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentType.Descriptor instead.
func (AgentType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_agent_service_proto_rawDescGZIP(), []int{0}
}

type ChatStreamResponse_MessageType int32

const (
	ChatStreamResponse_THINKING    ChatStreamResponse_MessageType = 0 // 思考中
	ChatStreamResponse_ACTION      ChatStreamResponse_MessageType = 1 // 执行动作
	ChatStreamResponse_OBSERVATION ChatStreamResponse_MessageType = 2 // 观察结果
	ChatStreamResponse_FINAL       ChatStreamResponse_MessageType = 3 // 最终答案
	ChatStreamResponse_ERROR       ChatStreamResponse_MessageType = 4 // 错误
	ChatStreamResponse_METADATA    ChatStreamResponse_MessageType = 5 // 元数据
)

// Enum value maps for ChatStreamResponse_MessageType.
var (
	ChatStreamResponse_MessageType_name = map[int32]string{
		0: "THINKING",
		1: "ACTION",
		2: "OBSERVATION",
		3: "FINAL",
		4: "ERROR",
		5: "METADATA",
	}
	ChatStreamResponse_MessageType_value = map[string]int32{
		"THINKING":    0,
		"ACTION":      1,
		"OBSERVATION": 2,
		"FINAL":       3,
		"ERROR":       4,
		"METADATA":    5,
	}
)

func (x ChatStreamResponse_MessageType) Enum() *ChatStreamResponse_MessageType {
	p := new(ChatStreamResponse_MessageType)
	*p = x
	return p
}

func (x ChatStreamResponse_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatStreamResponse_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_agent_service_proto_enumTypes[1].Descriptor()
}

func (ChatStreamResponse_MessageType) Type() protoreflect.EnumType {
	return &file_api_proto_agent_service_proto_enumTypes[1]
}

func (x ChatStreamResponse_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatStreamResponse_MessageType.Descriptor instead.
func (ChatStreamResponse_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_agent_service_proto_rawDescGZIP(), []int{3, 0}
}

// 空消息
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_service_proto_rawDescGZIP(), []int{0}
}

// 对话请求
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                                                             // 用户查询
	AgentType     AgentType              `protobuf:"varint,2,opt,name=agent_type,json=agentType,proto3,enum=agent.AgentType" json:"agent_type,omitempty"`                              // Agent类型
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`                                                                             // 模型名称 (e.g., "gpt-3.5-turbo")
	SystemPrompt  string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`                                           // 系统提示词（可选）
	MaxSteps      int32                  `protobuf:"varint,5,opt,name=max_steps,json=maxSteps,proto3" json:"max_steps,omitempty"`                                                      // 最大执行步数
	Config        map[string]string      `protobuf:"bytes,6,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外配置
	SessionId     string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                    // 会话ID（用于保持上下文）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_api_proto_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ChatRequest) GetAgentType() AgentType {
	if x != nil {
		return x.AgentType
	}
	return AgentType_REACT
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ChatRequest) GetMaxSteps() int32 {
	if x != nil {
		return x.MaxSteps
	}
	return 0
}

func (x *ChatRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 对话响应
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`                    // Agent响应
	AgentType     string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"` // 使用的Agent类型
	Metadata      *ExecutionMetadata     `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`                    // 执行元数据
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`                     // 是否成功
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                          // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_api_proto_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ChatResponse) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *ChatResponse) GetMetadata() *ExecutionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ChatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 流式对话响应
type ChatStreamResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Type          ChatStreamResponse_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=agent.ChatStreamResponse_MessageType" json:"type,omitempty"` // 消息类型
	Content       string                         `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                      // 消息内容
	Step          int32                          `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`                                           // 当前步骤
	Metadata      *ExecutionMetadata             `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`                                    // 执行元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamResponse) Reset() {
	*x = ChatStreamResponse{}
	mi := &file_api_proto_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamResponse) ProtoMessage() {}

func (x *ChatStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamResponse.ProtoReflect.Descriptor instead.
func (*ChatStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *ChatStreamResponse) GetType() ChatStreamResponse_MessageType {
	if x != nil {
		return x.Type
	}
	return ChatStreamResponse_THINKING
}

func (x *ChatStreamResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatStreamResponse) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *ChatStreamResponse) GetMetadata() *ExecutionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 执行元数据
type ExecutionMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalSteps      int32                  `protobuf:"varint,1,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`                  // 总步骤数
	ToolsCalled     int32                  `protobuf:"varint,2,opt,name=tools_called,json=toolsCalled,proto3" json:"tools_called,omitempty"`               // 调用的工具数量
	ToolNames       []string               `protobuf:"bytes,3,rep,name=tool_names,json=toolNames,proto3" json:"tool_names,omitempty"`                      // 使用的工具名称
	ExecutionTimeMs int64                  `protobuf:"varint,4,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"` // 执行时间（毫秒）
	State           string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`                                               // 执行状态
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionMetadata) Reset() {
	*x = ExecutionMetadata{}
	mi := &file_api_proto_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionMetadata) ProtoMessage() {}

func (x *ExecutionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionMetadata.ProtoReflect.Descriptor instead.
func (*ExecutionMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionMetadata) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *ExecutionMetadata) GetToolsCalled() int32 {
	if x != nil {
		return x.ToolsCalled
	}
	return 0
}

func (x *ExecutionMetadata) GetToolNames() []string {
	if x != nil {
		return x.ToolNames
	}
	return nil
}

func (x *ExecutionMetadata) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *ExecutionMetadata) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// Agent类型列表响应
type AgentTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*AgentTypeInfo       `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTypesResponse) Reset() {
	*x = AgentTypesResponse{}
	mi := &file_api_proto_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTypesResponse) ProtoMessage() {}

func (x *AgentTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTypesResponse.ProtoReflect.Descriptor instead.
func (*AgentTypesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *AgentTypesResponse) GetTypes() []*AgentTypeInfo {
	if x != nil {
		return x.Types
	}
	return nil
}

// Agent类型信息
type AgentTypeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AgentType              `protobuf:"varint,1,opt,name=type,proto3,enum=agent.AgentType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Available     bool                   `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTypeInfo) Reset() {
	*x = AgentTypeInfo{}
	mi := &file_api_proto_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTypeInfo) ProtoMessage() {}

func (x *AgentTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTypeInfo.ProtoReflect.Descriptor instead.
func (*AgentTypeInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *AgentTypeInfo) GetType() AgentType {
	if x != nil {
		return x.Type
	}
	return AgentType_REACT
}

func (x *AgentTypeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentTypeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentTypeInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

// 工具列表响应
type ToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolInfo            `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolsResponse) Reset() {
	*x = ToolsResponse{}
	mi := &file_api_proto_agent_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsResponse) ProtoMessage() {}

func (x *ToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsResponse.ProtoReflect.Descriptor instead.
func (*ToolsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_service_proto_rawDescGZIP(), []int{7}
}

func (x *ToolsResponse) GetTools() []*ToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

// 工具信息
type ToolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // Normal 或 Mcp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	mi := &file_api_proto_agent_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_service_proto_rawDescGZIP(), []int{8}
}

func (x *ToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_api_proto_agent_service_proto protoreflect.FileDescriptor

const file_api_proto_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/agent_service.proto\x12\x05agent\"\a\n" +
	"\x05Empty\"\xbe\x02\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12/\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\x0e2\x10.agent.AgentTypeR\tagentType\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12\x1b\n" +
	"\tmax_steps\x18\x05 \x01(\x05R\bmaxSteps\x126\n" +
	"\x06config\x18\x06 \x03(\v2\x1e.agent.ChatRequest.ConfigEntryR\x06config\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\fChatResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x124\n" +
	"\bmetadata\x18\x03 \x01(\v2\x18.agent.ExecutionMetadataR\bmetadata\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x91\x02\n" +
	"\x12ChatStreamResponse\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.agent.ChatStreamResponse.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04step\x18\x03 \x01(\x05R\x04step\x124\n" +
	"\bmetadata\x18\x04 \x01(\v2\x18.agent.ExecutionMetadataR\bmetadata\"\\\n" +
	"\vMessageType\x12\f\n" +
	"\bTHINKING\x10\x00\x12\n" +
	"\n" +
	"\x06ACTION\x10\x01\x12\x0f\n" +
	"\vOBSERVATION\x10\x02\x12\t\n" +
	"\x05FINAL\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\f\n" +
	"\bMETADATA\x10\x05\"\xb8\x01\n" +
	"\x11ExecutionMetadata\x12\x1f\n" +
	"\vtotal_steps\x18\x01 \x01(\x05R\n" +
	"totalSteps\x12!\n" +
	"\ftools_called\x18\x02 \x01(\x05R\vtoolsCalled\x12\x1d\n" +
	"\n" +
	"tool_names\x18\x03 \x03(\tR\ttoolNames\x12*\n" +
	"\x11execution_time_ms\x18\x04 \x01(\x03R\x0fexecutionTimeMs\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\"@\n" +
	"\x12AgentTypesResponse\x12*\n" +
	"\x05types\x18\x01 \x03(\v2\x14.agent.AgentTypeInfoR\x05types\"\x89\x01\n" +
	"\rAgentTypeInfo\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.agent.AgentTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\bR\tavailable\"6\n" +
	"\rToolsResponse\x12%\n" +
	"\x05tools\x18\x01 \x03(\v2\x0f.agent.ToolInfoR\x05tools\"T\n" +
	"\bToolInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type*4\n" +
	"\tAgentType\x12\t\n" +
	"\x05REACT\x10\x00\x12\t\n" +
	"\x05CHAIN\x10\x01\x12\b\n" +
	"\x04PLAN\x10\x02\x12\a\n" +
	"\x03SQL\x10\x032\xea\x01\n" +
	"\fAgentService\x12/\n" +
	"\x04Chat\x12\x12.agent.ChatRequest\x1a\x13.agent.ChatResponse\x12=\n" +
	"\n" +
	"StreamChat\x12\x12.agent.ChatRequest\x1a\x19.agent.ChatStreamResponse0\x01\x129\n" +
	"\x0eListAgentTypes\x12\f.agent.Empty\x1a\x19.agent.AgentTypesResponse\x12/\n" +
	"\tListTools\x12\f.agent.Empty\x1a\x14.agent.ToolsResponseB\x15Z\x13jas-agent/api/protob\x06proto3"

var (
	file_api_proto_agent_service_proto_rawDescOnce sync.Once
	file_api_proto_agent_service_proto_rawDescData []byte
)

func file_api_proto_agent_service_proto_rawDescGZIP() []byte {
	file_api_proto_agent_service_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_service_proto_rawDesc), len(file_api_proto_agent_service_proto_rawDesc)))
	})
	return file_api_proto_agent_service_proto_rawDescData
}

var file_api_proto_agent_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_agent_service_proto_goTypes = []any{
	(AgentType)(0),                      // 0: agent.AgentType
	(ChatStreamResponse_MessageType)(0), // 1: agent.ChatStreamResponse.MessageType
	(*Empty)(nil),                       // 2: agent.Empty
	(*ChatRequest)(nil),                 // 3: agent.ChatRequest
	(*ChatResponse)(nil),                // 4: agent.ChatResponse
	(*ChatStreamResponse)(nil),          // 5: agent.ChatStreamResponse
	(*ExecutionMetadata)(nil),           // 6: agent.ExecutionMetadata
	(*AgentTypesResponse)(nil),          // 7: agent.AgentTypesResponse
	(*AgentTypeInfo)(nil),               // 8: agent.AgentTypeInfo
	(*ToolsResponse)(nil),               // 9: agent.ToolsResponse
	(*ToolInfo)(nil),                    // 10: agent.ToolInfo
	nil,                                 // 11: agent.ChatRequest.ConfigEntry
}
var file_api_proto_agent_service_proto_depIdxs = []int32{
	0,  // 0: agent.ChatRequest.agent_type:type_name -> agent.AgentType
	11, // 1: agent.ChatRequest.config:type_name -> agent.ChatRequest.ConfigEntry
	6,  // 2: agent.ChatResponse.metadata:type_name -> agent.ExecutionMetadata
	1,  // 3: agent.ChatStreamResponse.type:type_name -> agent.ChatStreamResponse.MessageType
	6,  // 4: agent.ChatStreamResponse.metadata:type_name -> agent.ExecutionMetadata
	8,  // 5: agent.AgentTypesResponse.types:type_name -> agent.AgentTypeInfo
	0,  // 6: agent.AgentTypeInfo.type:type_name -> agent.AgentType
	10, // 7: agent.ToolsResponse.tools:type_name -> agent.ToolInfo
	3,  // 8: agent.AgentService.Chat:input_type -> agent.ChatRequest
	3,  // 9: agent.AgentService.StreamChat:input_type -> agent.ChatRequest
	2,  // 10: agent.AgentService.ListAgentTypes:input_type -> agent.Empty
	2,  // 11: agent.AgentService.ListTools:input_type -> agent.Empty
	4,  // 12: agent.AgentService.Chat:output_type -> agent.ChatResponse
	5,  // 13: agent.AgentService.StreamChat:output_type -> agent.ChatStreamResponse
	7,  // 14: agent.AgentService.ListAgentTypes:output_type -> agent.AgentTypesResponse
	9,  // 15: agent.AgentService.ListTools:output_type -> agent.ToolsResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_agent_service_proto_init() }
func file_api_proto_agent_service_proto_init() {
	if File_api_proto_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_service_proto_rawDesc), len(file_api_proto_agent_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_service_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_service_proto_depIdxs,
		EnumInfos:         file_api_proto_agent_service_proto_enumTypes,
		MessageInfos:      file_api_proto_agent_service_proto_msgTypes,
	}.Build()
	File_api_proto_agent_service_proto = out.File
	file_api_proto_agent_service_proto_goTypes = nil
	file_api_proto_agent_service_proto_depIdxs = nil
}
