// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"errors"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"jas-agent/agent/llm"
	"jas-agent/agent/rag/embedding"
	"jas-agent/internal/biz"
	"jas-agent/internal/conf"
	"jas-agent/internal/data"
	"jas-agent/internal/server"
	"jas-agent/internal/service"
)

import (
	_ "jas-agent/agent/examples/react/tools"
)

// Injectors from wire.go:

func wireApp(c *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	confServer := provideServerConfig(c)
	chat, err := newChat(c)
	if err != nil {
		return nil, nil, err
	}
	confData := provideDataConfig(c)
	db, err := data.NewDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	agentRepo := data.NewAgentRepo(dataData)
	agentFactory := biz.NewAgentFactory()
	agentUsecase := biz.NewAgentUsecase(chat, agentRepo, agentFactory, logger)
	mcpRepo := data.NewMCPRepo(dataData)
	mcpUsecase := biz.NewMcpUsecase(mcpRepo, logger)
	knowledgeBaseRepo := data.NewKnowledgeBaseRepo(dataData)
	documentRepo := data.NewDocumentRepo(dataData)
	embedder := newEmbedder(c)
	knowledgeUsecase := biz.NewKnowledgeUsecase(knowledgeBaseRepo, documentRepo, logger, c, embedder)
	agentService, err := service.NewAgentService(agentUsecase, mcpUsecase, knowledgeUsecase)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcServer := server.NewGRPCServer(confServer, agentService, logger)
	knowledgeServiceImpl := service.NewKnowledgeServiceImpl(knowledgeUsecase)
	httpServer := server.NewHTTPServer(confServer, agentService, knowledgeServiceImpl, logger)
	app := server.NewApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

var errMissingLLMConfig = errors.New("llm config is required")

func newChat(c *conf.Bootstrap) (llm.Chat, error) {
	if c.Llm == nil {
		return nil, errMissingLLMConfig
	}
	return llm.NewChat(&llm.Config{
		ApiKey:  c.Llm.ApiKey,
		BaseURL: c.Llm.BaseUrl,
	}), nil
}

func provideServerConfig(c *conf.Bootstrap) *conf.Server {
	if c == nil {
		return nil
	}
	return c.Server
}

func provideDataConfig(c *conf.Bootstrap) *conf.Data {
	if c == nil {
		return nil
	}
	return c.Data
}

func newEmbedder(c *conf.Bootstrap) embedding.Embedder {
	if c == nil {
		return nil
	}
	return embedding.NewOpenAIEmbedder(embedding.Config{
		ApiKey:  c.Llm.GetApiKey(),
		BaseURL: c.Llm.BaseUrl,
		Model:   "text-embedding-3-small",
	})
}
