// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"errors"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"jas-agent/agent/llm"
	"jas-agent/internal/biz"
	"jas-agent/internal/conf"
	"jas-agent/internal/data"
	"jas-agent/internal/server"
	"jas-agent/internal/service"
)

import (
	_ "jas-agent/agent/examples/react/tools"
)

// Injectors from wire.go:

func wireApp(c *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	confServer := provideServerConfig(c)
	llm := provideLLMConfig(c)
	chat, err := newChat(llm)
	if err != nil {
		return nil, nil, err
	}
	confData := provideDataConfig(c)
	db, err := data.NewDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	agentRepo := data.NewAgentRepo(dataData)
	mcpRepo := data.NewMCPRepo(dataData)
	agentUsecase := biz.NewAgentUsecase(chat, agentRepo, mcpRepo, logger)
	agentService, err := service.NewAgentService(agentUsecase)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcServer := server.NewGRPCServer(confServer, agentService, logger)
	httpServer := server.NewHTTPServer(confServer, agentService, logger)
	app := server.NewApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

var errMissingLLMConfig = errors.New("llm config is required")

func newChat(c *conf.LLM) (llm.Chat, error) {
	if c == nil {
		return nil, errMissingLLMConfig
	}
	return llm.NewChat(&llm.Config{
		ApiKey:  c.APIKey,
		BaseURL: c.BaseURL,
	}), nil
}

func provideServerConfig(c *conf.Bootstrap) *conf.Server {
	if c == nil {
		return nil
	}
	return c.Server
}

func provideDataConfig(c *conf.Bootstrap) *conf.Data {
	if c == nil {
		return nil
	}
	return c.Data
}

func provideLLMConfig(c *conf.Bootstrap) *conf.LLM {
	if c == nil {
		return nil
	}
	return c.LLM
}
